service: video-notification

frameworkVersion: "3"
package:
  individually: true

provider:
  name: aws
  stage: dev
  runtime: nodejs20.x
  region: us-east-1
  environment:
    TEST: test

custom:
  esbuild:
    bundle: true
    minify: true
    sourcemap: true
    external:
      - knex
    watch:
      pattern: "src/**/*.ts"
      ignore: "**/*.test.ts"

plugins:
  - serverless-esbuild
  - serverless-offline

functions:
  send-notification:
    handler: src/app/handlers/send-notification/index.handler
