name: Deploy

on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, edited, reopened]
    branches:
      - main

env:
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

jobs:
  ci:
    name: CI Pipeline
    runs-on: ubuntu-latest
    if: ${{ github.event_name == 'pull_request' || github.event_name == 'push' }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node
        uses: actions/setup-node@v2
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm ci

      - name: Validate lint
        run: npm run lint

      - name: Running tests
        run: npm run test

      - name: SonarQube Scan
        uses: SonarSource/sonarqube-scan-action@v4
        env:
          SONAR_TOKEN: ${{ secrets. SONARCLOUD_TOKEN }}
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    needs: ci
    if: github.event_name == 'push'

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install Serverless
        run: npm i -g serverless@3.39.0

      - name: Install Serverless ESbuild
        run: serverless plugin install -n serverless-esbuild

      - name: Serverless Package
        run: serverless package --package artifacts

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Upload to S3
        id: upload
        run: |
          aws s3 cp ./artifacts/send-notification.zip s3://cloud-burger-artifacts/send-notification.zip
